language: cpp

compiler:
  - gcc
  - clang

sudo: true

install:
  - sudo add-apt-repository -y ppa:beineri/opt-qt591-trusty
  - sudo apt-get -qq update
  - sudo apt-get -y install qt59-meta-minimal

before_script:
  - /opt/qt59/bin/qmake -r 'CONFIG+=debug gcov'
  - make -s -j$(getconf _NPROCESSORS_ONLN)

script:
  - make -s check
